project_id = "zdradwiudsuzavsexytt"

[functions.admin-login]
verify_jwt = false

[functions.consulta-publica]
verify_jwt = false

[functions.upload-publico]
verify_jwt = false

[functions.enviar-email]
verify_jwt = false

[functions.notificar-status]
verify_jwt = false

[functions.enviar-formulario]
verify_jwt = false