-- Engine de status de processo com transições configuráveis

-- 1) Novos status solicitados (mantém compatibilidade com enum legado)
ALTER TYPE public.status_solicitacao ADD VALUE IF NOT EXISTS 'SOLICITADO';
ALTER TYPE public.status_solicitacao ADD VALUE IF NOT EXISTS 'EM_ANALISE';
ALTER TYPE public.status_solicitacao ADD VALUE IF NOT EXISTS 'PENDENTE';
ALTER TYPE public.status_solicitacao ADD VALUE IF NOT EXISTS 'APROVADO';
ALTER TYPE public.status_solicitacao ADD VALUE IF NOT EXISTS 'FATURADO';
ALTER TYPE public.status_solicitacao ADD VALUE IF NOT EXISTS 'FINALIZADO';

-- 2) Catálogo de status do motor
CREATE TABLE IF NOT EXISTS public.process_status (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code TEXT NOT NULL UNIQUE,
  status_label TEXT NOT NULL,
  ordem INTEGER NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.process_status_transitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_status TEXT NOT NULL,
  to_status TEXT NOT NULL,
  acao TEXT NOT NULL,
  requires_validation BOOLEAN NOT NULL DEFAULT false,
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT process_status_transitions_unique UNIQUE (from_status, to_status, acao)
);

ALTER TABLE public.process_status_transitions
  ADD CONSTRAINT process_status_transitions_from_fk
  FOREIGN KEY (from_status) REFERENCES public.process_status(status_code)
  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE public.process_status_transitions
  ADD CONSTRAINT process_status_transitions_to_fk
  FOREIGN KEY (to_status) REFERENCES public.process_status(status_code)
  ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS idx_process_status_ativo_ordem
  ON public.process_status(ativo, ordem);

CREATE INDEX IF NOT EXISTS idx_process_status_transitions_lookup
  ON public.process_status_transitions(from_status, to_status, acao)
  WHERE ativo = true;

ALTER TABLE public.process_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.process_status_transitions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can view process_status" ON public.process_status;
CREATE POLICY "Authenticated can view process_status"
  ON public.process_status
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Only admins can manage process_status" ON public.process_status;
CREATE POLICY "Only admins can manage process_status"
  ON public.process_status
  FOR ALL
  USING (has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS "Authenticated can view process_status_transitions" ON public.process_status_transitions;
CREATE POLICY "Authenticated can view process_status_transitions"
  ON public.process_status_transitions
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Only admins can manage process_status_transitions" ON public.process_status_transitions;
CREATE POLICY "Only admins can manage process_status_transitions"
  ON public.process_status_transitions
  FOR ALL
  USING (has_role(auth.uid(), 'admin'::app_role));

-- 3) Seed: status iniciais + legados para compatibilidade
INSERT INTO public.process_status (status_code, status_label, ordem, ativo)
VALUES
  ('SOLICITADO', 'Solicitado', 10, true),
  ('EM_ANALISE', 'Em análise', 20, true),
  ('PENDENTE', 'Pendente', 30, true),
  ('APROVADO', 'Aprovado', 40, true),
  ('FATURADO', 'Faturado', 50, true),
  ('FINALIZADO', 'Finalizado', 60, true),
  ('aguardando_confirmacao', 'Aguardando confirmação (legado)', 110, true),
  ('cancelado', 'Cancelado (legado)', 120, true),
  ('recusado', 'Recusado (legado)', 130, true),
  ('confirmado_aguardando_vistoria', 'Confirmado aguardando vistoria (legado)', 140, true),
  ('confirmado_aguardando_servico', 'Confirmado aguardando serviço (legado)', 145, true),
  ('vistoria_finalizada', 'Vistoria finalizada (legado)', 150, true),
  ('vistoriado_com_pendencia', 'Vistoriado com pendência (legado)', 160, true),
  ('nao_vistoriado', 'Não vistoriado (legado)', 170, true)
ON CONFLICT (status_code) DO UPDATE
SET
  status_label = EXCLUDED.status_label,
  ordem = EXCLUDED.ordem,
  ativo = EXCLUDED.ativo,
  updated_at = now();

-- 4) Seed: transições padrão
INSERT INTO public.process_status_transitions (from_status, to_status, acao, requires_validation, ativo)
VALUES
  ('SOLICITADO', 'EM_ANALISE', 'iniciar_analise', false, true),
  ('EM_ANALISE', 'PENDENTE', 'solicitar_ajuste', true, true),
  ('PENDENTE', 'EM_ANALISE', 'retomar_analise', true, true),
  ('EM_ANALISE', 'APROVADO', 'aprovar', true, true),
  ('APROVADO', 'FATURADO', 'faturar', true, true),
  ('FATURADO', 'FINALIZADO', 'finalizar', false, true),
  ('EM_ANALISE', 'recusado', 'recusar', true, true),
  ('APROVADO', 'cancelado', 'cancelar', true, true),
  ('aguardando_confirmacao', 'confirmado_aguardando_vistoria', 'aprovar_setores', true, true),
  ('aguardando_confirmacao', 'recusado', 'reprovar_setores', true, true),
  ('confirmado_aguardando_vistoria', 'vistoria_finalizada', 'finalizar_vistoria', true, true),
  ('confirmado_aguardando_vistoria', 'vistoriado_com_pendencia', 'registrar_pendencia', true, true),
  ('confirmado_aguardando_vistoria', 'nao_vistoriado', 'nao_vistoriar', true, true),
  ('confirmado_aguardando_servico', 'FINALIZADO', 'concluir_servico', false, true),
  ('vistoriado_com_pendencia', 'EM_ANALISE', 'reanalisar', true, true)
ON CONFLICT (from_status, to_status, acao) DO UPDATE
SET
  requires_validation = EXCLUDED.requires_validation,
  ativo = EXCLUDED.ativo,
  updated_at = now();

-- 5) Engine transacional de mudança de status + auditoria
CREATE OR REPLACE FUNCTION public.process_status_engine(
  p_solicitacao_id UUID,
  p_to_status TEXT,
  p_acao TEXT,
  p_usuario_id UUID DEFAULT auth.uid(),
  p_requires_validation BOOLEAN DEFAULT false,
  p_detalhes TEXT DEFAULT NULL
)
RETURNS public.solicitacoes
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_solicitacao public.solicitacoes%ROWTYPE;
  v_transition public.process_status_transitions%ROWTYPE;
  v_from_status TEXT;
BEGIN
  IF p_usuario_id IS NULL THEN
    RAISE EXCEPTION 'Usuário obrigatório para processar transição de status';
  END IF;

  SELECT *
  INTO v_solicitacao
  FROM public.solicitacoes
  WHERE id = p_solicitacao_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Solicitação % não encontrada', p_solicitacao_id;
  END IF;

  v_from_status := v_solicitacao.status::TEXT;

  SELECT *
  INTO v_transition
  FROM public.process_status_transitions
  WHERE from_status = v_from_status
    AND to_status = p_to_status
    AND acao = p_acao
    AND ativo = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transição inválida: % --(%)-> %', v_from_status, p_acao, p_to_status;
  END IF;

  IF v_transition.requires_validation AND NOT p_requires_validation THEN
    RAISE EXCEPTION 'Ação % requer validação explícita', p_acao;
  END IF;

  UPDATE public.solicitacoes
  SET
    status = p_to_status::public.status_solicitacao,
    updated_at = now()
  WHERE id = p_solicitacao_id
  RETURNING * INTO v_solicitacao;

  IF to_regclass('public.audit_log') IS NOT NULL
     AND to_regprocedure('public.insert_audit_log(uuid,uuid,text,text,text,uuid)') IS NOT NULL THEN
    PERFORM public.insert_audit_log(
      p_solicitacao_id,
      p_usuario_id,
      'status_transition',
      COALESCE(
        p_detalhes,
        format('status: %s -> %s | acao: %s', v_from_status, p_to_status, p_acao)
      ),
      'solicitacoes',
      p_solicitacao_id
    );
  END IF;

  RETURN v_solicitacao;
END;
$$;

GRANT EXECUTE ON FUNCTION public.process_status_engine(UUID, TEXT, TEXT, UUID, BOOLEAN, TEXT) TO authenticated;
